name: Docker Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Run tests
      run: echo "Testler burada çalışacak"

    - name: Build Docker image with no cache
      run: docker build --no-cache -t yourdockerhubusername/yourimagename:latest .

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "yourdockerhubusername" --password-stdin

    - name: Push Docker image
      run: docker push yourdockerhubusername/yourimagename:latest
