name: Finans Payment Pipeline

on:
  push:
    branches: [main]
  pull_request: # PR'lar için de çalışsın
    branches: [main]
  workflow_dispatch: # Manuel çalıştırmaya izin verir

env:
  IMAGE_NAME: ozturk25/payment-service # Docker Hub kullanıcı adınız/imaj adınız
  AWS_REGION: eu-central-1

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions: # Gerekli izinler
      contents: read # Kodu çekmek için
      packages: write # Docker Hub'a push yapmak için
      security-events: write # Trivy SARIF raporunu yüklemek için
      id-token: write # AWS kimlik doğrulaması için OIDC kullanılıyorsa (eğer kullanıyorsanız)

    steps:
      - name: Kodu Çıkart
        uses: actions/checkout@v4

      - name: AWS Kimlik Bilgilerini Yapılandır
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          # Eğer OIDC kullanıyorsanız (daha güvenli), yukarıdaki satırları yorumlayıp aşağıdaki rolü kullanın:
          # role-to-assume: arn:aws:iam::[SİZİN_AWS_ACCOUNT_ID'NİZ]:role/YOUR_GITHUB_ACTIONS_ROLE_NAME # <-- Bu rolü kendi IAM rolünüzle değiştirin
          # duration-seconds: 900 # Rol oturumunun süresi (isteğe bağlı)

      - name: Docker Buildx Kurulumu
        uses: docker/setup-buildx-action@v3

      - name: Docker İmajını Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
          load: true

      - name: Testleri Çalıştır
        run: |
          if [ -d "tests" ]; then
            echo "Tests dizini bulundu. Testler çalıştırılıyor..."
            docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} python -m pytest tests/
          else
            echo "Tests dizini bulunamadı, testler atlanıyor."
            exit 0
          fi

      - name: Trivy Güvenlik Taraması
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Trivy Sonuçlarını Yükle (SARIF)
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub'a Gönder
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      # --- ECS DAĞITIMININ YENİ BÖLÜMÜ BAŞLANGICI ---
      - name: ECS Görev Tanımını Kaydet
        id: register-task-definition # Bu adıma bir ID veriyoruz
        uses: aws-actions/amazon-ecs-register-task-definition@v1 # Yeni aksiyon: Görev tanımı kaydetme
        with:
          task-definition: task-definition.json # Kök dizindeki task-definition.json dosyamız
          # Görev tanımındaki "image" alanını dinamik olarak güncellemek için
          # "container-name" ve "image" parametreleri kullanılır.
          # "container-name" task-definition.json içindeki "name" alanı ile eşleşmeli
          container-name: payment-service
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }} # Dağıtılacak gerçek imaj
          # Eğer task-definition.json dosyanızda başka yer tutucularınız varsa (örn. "log-group" gibi),
          # onları da burada "log-group: /ecs/my-app" gibi belirtebilirsiniz.

      - name: ECS Servisini Güncelle
        uses: aws-actions/amazon-ecs-deploy-service@v1 # Yeni aksiyon: Servisi güncelleme
        with:
          service: payment-service # Güncellenecek ECS Servisi
          cluster: payment-cluster # Servisin bulunduğu ECS Kümesi
          # Önceki adımda kaydedilen görev tanımının ARN'ini kullanıyoruz
          task-definition: ${{ steps.register-task-definition.outputs.task-definition-arn }}
          # İsteğe bağlı: Yeni bir dağıtım yapmaya zorla (Eğer servis güncellenmediyse bile)
          # force-new-deployment: true

      # --- ECS DAĞITIMININ YENİ BÖLÜMÜ SONU ---

      - name: Slack Bildirimi
        uses: slackapi/slack-github-action@v1.24.0
        if: success() || failure()
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅ Deploy Başarılı' || '❌ Deploy Başarısız' }}: ${{ env.IMAGE_NAME }}:${{ github.sha }}",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ job.status == 'success' && '✅ *Deploy Tamamlandı*' || '❌ *Deploy Başarısız Oldu*' }} \n*Image:* `${{ env.IMAGE_NAME }}:${{ github.sha }}` \n*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                }
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
