name: Finans Payment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ozturk25/1.haftaslack # <--- Güncellendi: Docker Hub kullanıcı adınız/imaj adınız
  AWS_REGION: eu-central-1

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Kodu çekmek için
      packages: write # Docker Hub'a push yapmak için
      security-events: write # Trivy SARIF raporunu yüklemek için
      id-token: write # AWS kimlik doğrulaması için OIDC kullanılıyorsa

    steps:
      - name: Kodu Çıkart
        uses: actions/checkout@v4

      - name: AWS Kimlik Bilgilerini Yapılandır
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          # Eğer OIDC kullanıyorsanız (daha güvenli), yukarıdaki satırları yorumlayıp aşağıdaki rolü kullanın:
          # role-to-assume: arn:aws:iam::[SİZİN_AWS_ACCOUNT_ID'NİZ]:role/YOUR_GITHUB_ACTIONS_ROLE_NAME
          # duration-seconds: 900

      - name: Docker Buildx Kurulumu
        uses: docker/setup-buildx-action@v3

      - name: Docker İmajını Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
          load: true

      - name: Testleri Çalıştır
        run: |
          if [ -d "tests" ]; then
            echo "Tests dizini bulundu. Testler çalıştırılıyor..."
            docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} python -m pytest tests/
          else
            echo "Tests dizini bulunamadı, testler atlanıyor."
            exit 0
          fi

      - name: Trivy Güvenlik Taraması
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif' # <-- Trivy çıktısı bu dosyaya yazılacak

      - name: Trivy Sonuçlarını Yükle (SARIF)
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Trivy çıktısının mutlak yolunu belirtiyoruz
          sarif_file: '${{ github.workspace }}/trivy-results.sarif' # <--- Düzeltildi!

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub'a Gönder
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      - name: ECS'ye Dağıt
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: payment-service # task-definition.json'daki konteynerin "name" alanı
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }} # Konteynerin atanacak TAM imaj yolu
          service: payment-service # AWS ECS'deki servis adı (ECS konsolundan kontrol edin)
          cluster: payment-cluster
          wait-for-service-stability: true

      - name: Slack Bildirimi
        uses: slackapi/slack-github-action@v1.24.0
        if: success() || failure() # İş akışı başarılı olsa da başarısız olsa da bildirim gönder
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅ Deploy Başarılı' || '❌ Deploy Başarısız' }}: ${{ env.IMAGE_NAME }}:${{ github.sha }}",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ job.status == 'success' && '✅ *Deploy Tamamlandı*' || '❌ *Deploy Başarısız Oldu*' }} \n*Image:* `${{ env.IMAGE_NAME }}:${{ github.sha }}` \n*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                }
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
