name: Finans Payment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_NAME: ozturk25/payment-service
  AWS_REGION: eu-central-1

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      security-events: write
      id-token: write

    steps:
      - name: Kodu Çıkart
        uses: actions/checkout@v4

      - name: AWS Kimlik Bilgilerini Yapılandır
        uses: aws-actions/configure-aws-credentials@v4

      - name: Docker Buildx Kurulumu
        uses: docker/setup-buildx-action@v3

      - name: Docker İmajını Oluştur ve Yükle
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }},${{ env.IMAGE_NAME }}:latest
          load: true

      - name: Testleri Çalıştır
        run: |
          if [ -d "tests" ]; then
            echo "Tests dizini bulundu. Testler çalıştırılıyor..."
            docker run --rm ${{ env.IMAGE_NAME }}:${{ github.sha }} python -m pytest tests/
          else
            echo "Tests dizini bulunamadı, testler atlanıyor."
            exit 0
          fi

      - name: Trivy Güvenlik Taraması
        uses: aquasecurity/trivy-action@0.14.0
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          format: 'sarif'
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.sarif'

      - name: Trivy Sonuçlarını Yükle (SARIF)
        uses: github/codeql-action/upload-sarif@v3

      - name: Docker Hub'a Giriş Yap
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Hub'a Gönder
        run: |
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:latest

      # --- ECS DAĞITIMININ YENİ BÖLÜMÜ BAŞLANGICI ---
      - name: ECS Görev Tanımını Kaydet
        id: register-task-definition
        uses: aws-actions/amazon-ecs-register-task-definition@main # <-- Versiyonu main olarak değiştirildi
        with:
          task-definition: task-definition.json
          container-name: payment-service
          image: ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: ECS Servisini Güncelle
        uses: aws-actions/amazon-ecs-deploy-service@main # <-- Versiyonu main olarak değiştirildi
        with:
          service: payment-service
          cluster: payment-cluster
          task-definition: ${{ steps.register-task-definition.outputs.task-definition-arn }}
      # --- ECS DAĞITIMININ YENİ BÖLÜMÜ SONU ---

      - name: Slack Bildirimi
        uses: slackapi/slack-github-action@v1.24.0
        if: success() || failure()
        with:
          payload: |
            {
              "text": "${{ job.status == 'success' && '✅ Deploy Başarılı' || '❌ Deploy Başarısız' }}: ${{ env.IMAGE_NAME }}:${{ github.sha }}",
              "blocks": [{
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ job.status == 'success' && '✅ *Deploy Tamamlandı*' || '❌ *Deploy Başarısız Oldu*' }} \n*Image:* `${{ env.IMAGE_NAME }}:${{ github.sha }}` \n*Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }}>"
                }
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
